### ISSUE TITLE
Gnome Shell 43-45 compatibility

### ISSUE THREAD

**Issue by mjbogusz** [VeryCrazyDog/gnome-disable-gestures#5]
Hi,
could you check compatibility with Gnome Shell 43, 44 and 45 and update the extension's info?

From a quick skim, 43 and 44 shouldn't be a problem, however 45 introduces [breaking changes to extension.js](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extension-js) that might be an issue here.

I'm mostly interested in Gnome 43 as that's what Debian 12 ships with, so I'll try verifying compatibility with this one myself.

**Comment by VeryCrazyDog** [comment]
I no longer use GNOME in my work and I don't have the environment to test the compatibility. However I have updated the extension to mark it compatible with GNOME 43 and 44 so you can install and if that works.

As for GNOME 45, since it is not yet released and requires breaking change, I will publish a new version until someone who use GNOME 45 request it.

**Comment by dehuszar** [comment]
Just as an FYI, I manually installed the extension in Ubuntu 23.10 with Gnome 45 and it appears to be working splendidly.  Thank you for your work here.  :tada:
